# Generated by Django 4.0 on 2022-01-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_review_star_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='star_rating',
        ),
    ]
